gui:
  # Use the mocha catppuccin theme
  authorColors:
    '*': '#cdd6f4'
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
os:
  copyToClipboardCmd: 'printf "\033]52;c;$(printf %s {{text}} | base64 -w 0)\a" > /dev/tty'
